### PR TITLE
Try porting to pandoc 1.12

### PR DESCRIPTION
**Pull request by Blaisorblade**
I got started while upgrading my Haskell platform.
I followed [Pandoc's changelog](http://hackage.haskell.org/package/pandoc-1.13.1/changelog) to have an idea of how to proceed, but at least bibliography support is probably broken. I'm also not convinced that the "tex" format exists (there's no corresponding reader/writer), but I've left that in. (Why isn't there a datatype for formats? I see `String` is more extensible, but... well...)

### CODE REVIEW

**Comment by mpickering** [comment]
I have a working version now at https://github.com/mpickering/pandoc-lit

**Comment by Blaisorblade** [comment]
Sounds really cool! I've just built it with stack and stackage, using:

```
resolver: lts-3.11

# Local packages, usually specified by relative directory name
packages:
- '.'

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps: [regexpr-0.5.4, mtlparse-0.1.4.0]

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []
```
(`lts-3.15` should also work, haven't tried building it).

**Comment by mpickering** [comment]
@Blaisorblade Thanks for trying. When @Toxaris gives me the all clear I will upload it to hackage and stackage.

**Comment by Blaisorblade** [comment]
@mpickering Hi! Did you lose interest, or did this get stuck on some problem that could be solved? I understand @Toxaris did give you an OK by email.

**Comment by mpickering** [comment]
As far as I remember, it all works properly but I had to do some hacking to make it work properly for me. 
For example, I removed the option of using bird tacks for literate code and added a new directive which
didn't escape code blocks. Now that my thesis is finished, maybe I will find time to clean everything up but I'm not sure. People are welcome to try my branch if they want. 

The main problem is that I wanted to turn it into a filter so that a lot of the flags could be removed. However, this isn't possible as pandoc doesn't allow you to specify specific flags for filters.

**Pull request closed without merging**
